from appium.webdriver.common.touch_action import TouchAction
from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: android
    Package: TestProject.Generated.Tests.Android
    Test: sign_out_note9
    Generated by: TJ Kim (arche0840@gmail.com)
    Generated on 04/15/2022, 02:19:18
"""


@pytest.fixture()
def driver():
    capabilities = {
        "platformName": "Android",
        "udid": "287860acb13f7ece",
        "appPackage": "com.Classting",
        "appActivity": "com.Classting.MainActivity",
    }
    driver = webdriver.Remote(token="GeWPVxkDL49XzPz0Z4AaKh44m8er7fCFzgldZlXcyQg1",
                              project_name="android",
                              job_name="sign_out_note9",
                              desired_capabilities=capabilities)
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):

    # 1. Tap 'MY'
    my = driver.find_element(By.XPATH,
                             "//android.widget.TextView[@text = 'MY']")
    TouchAction(driver).tap(my).perform()

    # 2. Tap 'ANDROID.WIDGET.IMAGEVIEW'
    android_widget_imageview = driver.find_element(By.XPATH,
                                                   "//android.view.ViewGroup[2]/android.widget.ImageView")
    TouchAction(driver).tap(android_widget_imageview).perform()

    # 3. Make a Swipe gesture from ('574','1896') to ('562','938')
    driver.swipe(start_x=574, start_y=1896, end_x=562, end_y=938, duration=300)

    # 4. Make a Swipe gesture from ('574','1896') to ('562','938')
    driver.swipe(start_x=574, start_y=1896, end_x=562, end_y=938, duration=300)

    # 5. Click '로그아웃'
    _ = driver.find_element(By.XPATH,
                            "//android.widget.TextView[@text = '로그아웃']")
    _.click()
